//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="DataProviderServiceImplSoapBinding", Namespace="http://oka.goto10.pl")]
public partial class MyService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback getLiniaPictureBase64StringOperationCompleted;
    
    private System.Threading.SendOrPostCallback getLiniaPictureBase64BytesOperationCompleted;
    
    private System.Threading.SendOrPostCallback getScenaTextENOperationCompleted;
    
    private System.Threading.SendOrPostCallback getScenaTextDEOperationCompleted;
    
    private System.Threading.SendOrPostCallback getObiektTextENOperationCompleted;
    
    private System.Threading.SendOrPostCallback getObiektTextDEOperationCompleted;
    
    private System.Threading.SendOrPostCallback getLiniaPictureOperationCompleted;
    
    private System.Threading.SendOrPostCallback getLiniaPictureTypeOperationCompleted;
    
    /// <remarks/>
	public MyService() {
		this.Url = "http://52.28.65.193:8080//DataProvider/services/DataProviderServiceImpl";
    }
    
    /// <remarks/>
    public event getLiniaPictureBase64StringCompletedEventHandler getLiniaPictureBase64StringCompleted;
    
    /// <remarks/>
    public event getLiniaPictureBase64BytesCompletedEventHandler getLiniaPictureBase64BytesCompleted;
    
    /// <remarks/>
    public event getScenaTextENCompletedEventHandler getScenaTextENCompleted;
    
    /// <remarks/>
    public event getScenaTextDECompletedEventHandler getScenaTextDECompleted;
    
    /// <remarks/>
    public event getObiektTextENCompletedEventHandler getObiektTextENCompleted;
    
    /// <remarks/>
    public event getObiektTextDECompletedEventHandler getObiektTextDECompleted;
    
    /// <remarks/>
    public event getLiniaPictureCompletedEventHandler getLiniaPictureCompleted;
    
    /// <remarks/>
    public event getLiniaPictureTypeCompletedEventHandler getLiniaPictureTypeCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://oka.goto10.pl", ResponseNamespace="http://oka.goto10.pl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("getLiniaPictureBase64StringReturn")]
    public string getLiniaPictureBase64String(string nazwaLinii, int pictureNo) {
        object[] results = this.Invoke("getLiniaPictureBase64String", new object[] {
                    nazwaLinii,
                    pictureNo});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetLiniaPictureBase64String(string nazwaLinii, int pictureNo, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getLiniaPictureBase64String", new object[] {
                    nazwaLinii,
                    pictureNo}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndgetLiniaPictureBase64String(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void getLiniaPictureBase64StringAsync(string nazwaLinii, int pictureNo) {
        this.getLiniaPictureBase64StringAsync(nazwaLinii, pictureNo, null);
    }
    
    /// <remarks/>
    public void getLiniaPictureBase64StringAsync(string nazwaLinii, int pictureNo, object userState) {
        if ((this.getLiniaPictureBase64StringOperationCompleted == null)) {
            this.getLiniaPictureBase64StringOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetLiniaPictureBase64StringOperationCompleted);
        }
        this.InvokeAsync("getLiniaPictureBase64String", new object[] {
                    nazwaLinii,
                    pictureNo}, this.getLiniaPictureBase64StringOperationCompleted, userState);
    }
    
    private void OngetLiniaPictureBase64StringOperationCompleted(object arg) {
        if ((this.getLiniaPictureBase64StringCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getLiniaPictureBase64StringCompleted(this, new getLiniaPictureBase64StringCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://oka.goto10.pl", ResponseNamespace="http://oka.goto10.pl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("getLiniaPictureBase64BytesReturn", DataType="base64Binary")]
    public byte[] getLiniaPictureBase64Bytes(string nazwaLinii, int pictureNo) {
        object[] results = this.Invoke("getLiniaPictureBase64Bytes", new object[] {
                    nazwaLinii,
                    pictureNo});
        return ((byte[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetLiniaPictureBase64Bytes(string nazwaLinii, int pictureNo, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getLiniaPictureBase64Bytes", new object[] {
                    nazwaLinii,
                    pictureNo}, callback, asyncState);
    }
    
    /// <remarks/>
    public byte[] EndgetLiniaPictureBase64Bytes(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((byte[])(results[0]));
    }
    
    /// <remarks/>
    public void getLiniaPictureBase64BytesAsync(string nazwaLinii, int pictureNo) {
        this.getLiniaPictureBase64BytesAsync(nazwaLinii, pictureNo, null);
    }
    
    /// <remarks/>
    public void getLiniaPictureBase64BytesAsync(string nazwaLinii, int pictureNo, object userState) {
        if ((this.getLiniaPictureBase64BytesOperationCompleted == null)) {
            this.getLiniaPictureBase64BytesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetLiniaPictureBase64BytesOperationCompleted);
        }
        this.InvokeAsync("getLiniaPictureBase64Bytes", new object[] {
                    nazwaLinii,
                    pictureNo}, this.getLiniaPictureBase64BytesOperationCompleted, userState);
    }
    
    private void OngetLiniaPictureBase64BytesOperationCompleted(object arg) {
        if ((this.getLiniaPictureBase64BytesCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getLiniaPictureBase64BytesCompleted(this, new getLiniaPictureBase64BytesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://oka.goto10.pl", ResponseNamespace="http://oka.goto10.pl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("getScenaTextENReturn")]
    public string getScenaTextEN(string linia, int scena) {
        object[] results = this.Invoke("getScenaTextEN", new object[] {
                    linia,
                    scena});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetScenaTextEN(string linia, int scena, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getScenaTextEN", new object[] {
                    linia,
                    scena}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndgetScenaTextEN(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void getScenaTextENAsync(string linia, int scena) {
        this.getScenaTextENAsync(linia, scena, null);
    }
    
    /// <remarks/>
    public void getScenaTextENAsync(string linia, int scena, object userState) {
        if ((this.getScenaTextENOperationCompleted == null)) {
            this.getScenaTextENOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetScenaTextENOperationCompleted);
        }
        this.InvokeAsync("getScenaTextEN", new object[] {
                    linia,
                    scena}, this.getScenaTextENOperationCompleted, userState);
    }
    
    private void OngetScenaTextENOperationCompleted(object arg) {
        if ((this.getScenaTextENCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getScenaTextENCompleted(this, new getScenaTextENCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://oka.goto10.pl", ResponseNamespace="http://oka.goto10.pl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("getScenaTextDEReturn")]
    public string getScenaTextDE(string linia, int scena) {
        object[] results = this.Invoke("getScenaTextDE", new object[] {
                    linia,
                    scena});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetScenaTextDE(string linia, int scena, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getScenaTextDE", new object[] {
                    linia,
                    scena}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndgetScenaTextDE(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void getScenaTextDEAsync(string linia, int scena) {
        this.getScenaTextDEAsync(linia, scena, null);
    }
    
    /// <remarks/>
    public void getScenaTextDEAsync(string linia, int scena, object userState) {
        if ((this.getScenaTextDEOperationCompleted == null)) {
            this.getScenaTextDEOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetScenaTextDEOperationCompleted);
        }
        this.InvokeAsync("getScenaTextDE", new object[] {
                    linia,
                    scena}, this.getScenaTextDEOperationCompleted, userState);
    }
    
    private void OngetScenaTextDEOperationCompleted(object arg) {
        if ((this.getScenaTextDECompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getScenaTextDECompleted(this, new getScenaTextDECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://oka.goto10.pl", ResponseNamespace="http://oka.goto10.pl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("getObiektTextENReturn")]
    public string getObiektTextEN(string linia) {
        object[] results = this.Invoke("getObiektTextEN", new object[] {
                    linia});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetObiektTextEN(string linia, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getObiektTextEN", new object[] {
                    linia}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndgetObiektTextEN(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void getObiektTextENAsync(string linia) {
        this.getObiektTextENAsync(linia, null);
    }
    
    /// <remarks/>
    public void getObiektTextENAsync(string linia, object userState) {
        if ((this.getObiektTextENOperationCompleted == null)) {
            this.getObiektTextENOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetObiektTextENOperationCompleted);
        }
        this.InvokeAsync("getObiektTextEN", new object[] {
                    linia}, this.getObiektTextENOperationCompleted, userState);
    }
    
    private void OngetObiektTextENOperationCompleted(object arg) {
        if ((this.getObiektTextENCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getObiektTextENCompleted(this, new getObiektTextENCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://oka.goto10.pl", ResponseNamespace="http://oka.goto10.pl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("getObiektTextDEReturn")]
    public string getObiektTextDE(string linia) {
        object[] results = this.Invoke("getObiektTextDE", new object[] {
                    linia});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetObiektTextDE(string linia, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getObiektTextDE", new object[] {
                    linia}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndgetObiektTextDE(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void getObiektTextDEAsync(string linia) {
        this.getObiektTextDEAsync(linia, null);
    }
    
    /// <remarks/>
    public void getObiektTextDEAsync(string linia, object userState) {
        if ((this.getObiektTextDEOperationCompleted == null)) {
            this.getObiektTextDEOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetObiektTextDEOperationCompleted);
        }
        this.InvokeAsync("getObiektTextDE", new object[] {
                    linia}, this.getObiektTextDEOperationCompleted, userState);
    }
    
    private void OngetObiektTextDEOperationCompleted(object arg) {
        if ((this.getObiektTextDECompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getObiektTextDECompleted(this, new getObiektTextDECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://oka.goto10.pl", ResponseNamespace="http://oka.goto10.pl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("getLiniaPictureReturn", DataType="base64Binary")]
    public byte[] getLiniaPicture(string nazwaLinii, int pictureNo) {
        object[] results = this.Invoke("getLiniaPicture", new object[] {
                    nazwaLinii,
                    pictureNo});
        return ((byte[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetLiniaPicture(string nazwaLinii, int pictureNo, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getLiniaPicture", new object[] {
                    nazwaLinii,
                    pictureNo}, callback, asyncState);
    }
    
    /// <remarks/>
    public byte[] EndgetLiniaPicture(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((byte[])(results[0]));
    }
    
    /// <remarks/>
    public void getLiniaPictureAsync(string nazwaLinii, int pictureNo) {
        this.getLiniaPictureAsync(nazwaLinii, pictureNo, null);
    }
    
    /// <remarks/>
    public void getLiniaPictureAsync(string nazwaLinii, int pictureNo, object userState) {
        if ((this.getLiniaPictureOperationCompleted == null)) {
            this.getLiniaPictureOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetLiniaPictureOperationCompleted);
        }
        this.InvokeAsync("getLiniaPicture", new object[] {
                    nazwaLinii,
                    pictureNo}, this.getLiniaPictureOperationCompleted, userState);
    }
    
    private void OngetLiniaPictureOperationCompleted(object arg) {
        if ((this.getLiniaPictureCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getLiniaPictureCompleted(this, new getLiniaPictureCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://oka.goto10.pl", ResponseNamespace="http://oka.goto10.pl", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("getLiniaPictureTypeReturn")]
    public string getLiniaPictureType(string nazwaLinii, int pictureNo) {
        object[] results = this.Invoke("getLiniaPictureType", new object[] {
                    nazwaLinii,
                    pictureNo});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetLiniaPictureType(string nazwaLinii, int pictureNo, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getLiniaPictureType", new object[] {
                    nazwaLinii,
                    pictureNo}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndgetLiniaPictureType(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void getLiniaPictureTypeAsync(string nazwaLinii, int pictureNo) {
        this.getLiniaPictureTypeAsync(nazwaLinii, pictureNo, null);
    }
    
    /// <remarks/>
    public void getLiniaPictureTypeAsync(string nazwaLinii, int pictureNo, object userState) {
        if ((this.getLiniaPictureTypeOperationCompleted == null)) {
            this.getLiniaPictureTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetLiniaPictureTypeOperationCompleted);
        }
        this.InvokeAsync("getLiniaPictureType", new object[] {
                    nazwaLinii,
                    pictureNo}, this.getLiniaPictureTypeOperationCompleted, userState);
    }
    
    private void OngetLiniaPictureTypeOperationCompleted(object arg) {
        if ((this.getLiniaPictureTypeCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getLiniaPictureTypeCompleted(this, new getLiniaPictureTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void getLiniaPictureBase64StringCompletedEventHandler(object sender, getLiniaPictureBase64StringCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getLiniaPictureBase64StringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getLiniaPictureBase64StringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void getLiniaPictureBase64BytesCompletedEventHandler(object sender, getLiniaPictureBase64BytesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getLiniaPictureBase64BytesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getLiniaPictureBase64BytesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public byte[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((byte[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void getScenaTextENCompletedEventHandler(object sender, getScenaTextENCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getScenaTextENCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getScenaTextENCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void getScenaTextDECompletedEventHandler(object sender, getScenaTextDECompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getScenaTextDECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getScenaTextDECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void getObiektTextENCompletedEventHandler(object sender, getObiektTextENCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getObiektTextENCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getObiektTextENCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void getObiektTextDECompletedEventHandler(object sender, getObiektTextDECompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getObiektTextDECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getObiektTextDECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void getLiniaPictureCompletedEventHandler(object sender, getLiniaPictureCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getLiniaPictureCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getLiniaPictureCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public byte[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((byte[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void getLiniaPictureTypeCompletedEventHandler(object sender, getLiniaPictureTypeCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getLiniaPictureTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getLiniaPictureTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}
